# Generated by Django 5.2.6 on 2025-09-16 18:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('hat', 'Hat'), ('jersey', 'Jersey'), ('pant', 'Pant'), ('sock', 'Sock'), ('shoe', 'Shoe'), ('boxer', 'Boxer')], default='lain lain', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
